
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
//import java.util.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Comparator;
import java.rmi.*;
import java.awt.event.*;
import java.net.MalformedURLException;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableRowSorter;


public class InterfazResena extends javax.swing.JFrame {

    private Item item;
    private String argumentos[];
    private ServicioResena srv_resena;
    private int valoracion;
    private Usuario usuario;
    private String[] datos;


    /**
     * Creates new form InicioAdminFrame
     */
    public InterfazResena(String args[],Item item, Usuario usuario) {
  this.item=item;
  argumentos=args;
  this.usuario=usuario;
        initComponents();


  try{
        srv_resena = (ServicioResena) Naming.lookup("//"+argumentos[0]+":"+argumentos[1]+"/ServicioResena");
  datos = srv_resena.extraerUltimaResena(item);

  Titulo_resena_otro.setText(datos[1]);
  Texto_resena_otro.setText(datos[0]);
  if (datos[2]=="")
      datos[2]="0";
  valoracion(Integer.parseInt(datos[2]));

  } catch (RemoteException ex){}
  catch (Exception ex){}


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cerrar_Sesion = new javax.swing.JButton();
        TituloItem_Tipo = new javax.swing.JLabel();
        NombreUsuario1 = new javax.swing.JLabel();
        PuntuacionGeneral = new javax.swing.JLabel();
        Estrella2 = new javax.swing.JLabel();
        Estrella1 = new javax.swing.JLabel();
        Estrella5 = new javax.swing.JLabel();
        Estrella3 = new javax.swing.JLabel();
        Estrella4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ResenaUsuario1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResenaAEscribir = new javax.swing.JTextArea();
        EnviarResena = new javax.swing.JButton();
        PuntuacionUsuario1 = new javax.swing.JLabel();
  jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        ResenaUsuario2 = new javax.swing.JTextPane();
        PuntuacionUsuario2 = new javax.swing.JLabel();
        NombreUsuario2 = new javax.swing.JLabel();
  Titulo_resena = new javax.swing.JTextField();
  Titulo_resena_otro = new javax.swing.JLabel();
  Texto_resena_otro = new javax.swing.JTextArea();
  PanelEstrellasMario = new javax.swing.JPanel();
        estrella5 = new javax.swing.JLabel();
        estrella1 = new javax.swing.JLabel();
        estrella2 = new javax.swing.JLabel();
        estrella3 = new javax.swing.JLabel();
        estrella4 = new javax.swing.JLabel();


  Texto_resena_otro.setLineWrap(true);
        Texto_resena_otro.setWrapStyleWord(true);

  ResenaAEscribir.setLineWrap(true);
        ResenaAEscribir.setWrapStyleWord(true);

  Texto_resena_otro.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("RESEÑAS");

        Volver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Volver.setText("VOLVER");
        Volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
  Volver.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
    InterfazUsuario app = new InterfazUsuario(argumentos,usuario);

  app.empezar();
      Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
          setVisible(false);
          dispose();

            }
        });
    timer.start(); // Iniciar el temporizador

            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Logochiquito.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));

        Cerrar_Sesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cerrar_Sesion.setText("CERRAR SESION");
        Cerrar_Sesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
         Cerrar_Sesion.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
 InterfazPrincipal app = new InterfazPrincipal(argumentos);

  app.empezar();
      Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
          setVisible(false);
          dispose();

            }
        });
    timer.start(); // Iniciar el temporizador





            }
        });

        TituloItem_Tipo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        TituloItem_Tipo.setText("Item: "+item.getNombre()+" - Tipo: "+item.getTipoArticulo());

        NombreUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        NombreUsuario1.setText("NombreUsuario1:");

        PuntuacionGeneral.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        PuntuacionGeneral.setText("OTROS USUARIOS DICEN:");


   Estrella1.setText("\u2606");
   Estrella1.setFont(new java.awt.Font("Segoe UI", 1, 55));
   // Agregamos un MouseListener a cada estrella para manejar el clic
        Estrella1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                rellenaEstrellas(1); // Llama a la función fillStars con el número de estrella clicada
            }
        });

  Estrella2.setText("\u2606");
  Estrella2.setFont(new java.awt.Font("Segoe UI", 1, 55));
  Estrella2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                rellenaEstrellas(2); // Llama a la función fillStars con el número de estrella clicada
            }
        });

       Estrella3.setText("\u2606");
       Estrella3.setFont(new java.awt.Font("Segoe UI", 1, 55));
       Estrella3.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                rellenaEstrellas(3); // Llama a la función fillStars con el número de estrella clicada
            }
        });

       Estrella4.setText("\u2606");
       Estrella4.setFont(new java.awt.Font("Segoe UI", 1, 55));
       Estrella4.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                rellenaEstrellas(4); // Llama a la función fillStars con el número de estrella clicada
            }
        });

        Estrella5.setText("\u2606");
  Estrella5.setFont(new java.awt.Font("Segoe UI", 1, 55));
  Estrella5.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                rellenaEstrellas(5); // Llama a la función fillStars con el número de estrella clicada
            }
        });





        ResenaUsuario1.setEditable(false);
        ResenaUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ResenaUsuario1.setText("Aqui iria la reseña escrita");
        jScrollPane4.setViewportView(ResenaUsuario1);

        ResenaAEscribir.setColumns(20);
        ResenaAEscribir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        ResenaAEscribir.setRows(5);
        ResenaAEscribir.setText("Escribe una reseña");
        jScrollPane1.setViewportView(ResenaAEscribir);

        EnviarResena.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        EnviarResena.setText("ENVIAR RESEÑA");
        EnviarResena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
  EnviarResena.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

    envioResena();
    JOptionPane.showMessageDialog(null, "Su reseña ha sido registrada con éxito", "BigBox", JOptionPane.INFORMATION_MESSAGE);
    EnviarResena.setVisible(false);

            }
        });

  Titulo_resena.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Titulo_resena.setText("Escriba un título descriptivo");

        PuntuacionUsuario1.setText("Puntuación/5");

        ResenaUsuario2.setEditable(false);
        ResenaUsuario2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ResenaUsuario2.setText("Aqui iria la reseña escrita");
        jScrollPane5.setViewportView(ResenaUsuario2);

        PuntuacionUsuario2.setText("Puntuación/5");

        NombreUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        NombreUsuario2.setText("NombreUsuario2:");

  Titulo_resena_otro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        //Titulo_resena_otro.setText("Titulo de la reseña");


  Texto_resena_otro.setColumns(20);
        Texto_resena_otro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Texto_resena_otro.setRows(5);
        jScrollPane2.setViewportView(Texto_resena_otro);

  estrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("Star-icondef.jpg"))); // NOI18N

        estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Star-icondef.jpg"))); // NOI18N

        estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Star-icondef.jpg"))); // NOI18N

        estrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("Star-icondef.jpg"))); // NOI18N

        estrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("Star-icondef.jpg"))); // NOI18N

  javax.swing.GroupLayout PanelEstrellasMarioLayout = new javax.swing.GroupLayout(PanelEstrellasMario);
        PanelEstrellasMario.setLayout(PanelEstrellasMarioLayout);
        PanelEstrellasMarioLayout.setHorizontalGroup(
            PanelEstrellasMarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstrellasMarioLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(estrella1)
                .addGap(18, 18, 18)
                .addComponent(estrella2)
                .addGap(18, 18, 18)
                .addComponent(estrella3)
                .addGap(18, 18, 18)
                .addComponent(estrella4)
                .addGap(18, 18, 18)
                .addComponent(estrella5)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PanelEstrellasMarioLayout.setVerticalGroup(
            PanelEstrellasMarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstrellasMarioLayout.createSequentialGroup()
                .addGroup(PanelEstrellasMarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
         .addComponent(estrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(estrella2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estrella3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(estrella4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(estrella5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(0, 0, Short.MAX_VALUE))
        );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(661, 661, 661)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estrella1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnviarResena)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Estrella2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Estrella3)
                                        .addGap(18, 18, 18)
                                        .addComponent(Estrella4)
                                        .addGap(18, 18, 18)
                                        .addComponent(Estrella5))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloItem_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Titulo_resena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)))
                        .addGap(365, 365, 365)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo_resena_otro, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PuntuacionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelEstrellasMario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 828, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
);

layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TituloItem_Tipo)
                        .addGap(44, 44, 44)
                        .addComponent(Titulo_resena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(Estrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estrella2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estrella3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Estrella4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Estrella5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))


                        .addGap(87, 87, 87)
                        .addComponent(EnviarResena)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()

                        .addComponent(PuntuacionGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(PanelEstrellasMario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                        .addGap(18, 18, 18)
                        .addComponent(Titulo_resena_otro)
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cerrar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))))
);

pack();
    }

   // Método para colorear las estrellas hasta el índice dado
    private void rellenaEstrellas(int index) {
        JLabel[] estrellas = {Estrella1, Estrella2, Estrella3, Estrella4, Estrella5};
  valoracion=index;
        for (int i = 0; i < estrellas.length; i++) {
            if (i < index) {
                estrellas[i].setText("\u2605"); // Cambia el texto a la estrella llena
            } else {
                estrellas[i].setText("\u2606"); // Cambia el texto a la estrella vacía
            }
        }
    }


    private void valoracion(int valoracion){

   JLabel[] estrellas = {estrella1, estrella2, estrella3, estrella4, estrella5};

   for (int i = 0; i < estrellas.length; i++) {
            if (i < valoracion) {
                estrellas[i].setVisible(true);
            } else {
                estrellas[i].setVisible(false); // Cambia el texto a la estrella vacía
            }
    }



    }


    private void Cerrar_SesionActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */



    private void envioResena(){

  try {
    String tituloTexto = Titulo_resena.getText();
                String resenaTexto = ResenaAEscribir.getText();

     srv_resena.anadirResena(item,tituloTexto,resenaTexto,valoracion,usuario.getNombre());

     }
     catch(RemoteException ex){
         System.err.println("Error Remoto");
     }
     catch(Exception exc){
         System.err.println("Otro error");
     }





    }
    public void empezar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {





            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazResena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazResena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazResena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazResena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (Exception ex){
      java.util.logging.Logger.getLogger(InterfazResena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazResena(argumentos,item,usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Cerrar_Sesion;
    private javax.swing.JButton EnviarResena;
    private javax.swing.JLabel Estrella1;
    private javax.swing.JLabel Estrella2;
    private javax.swing.JLabel Estrella3;
    private javax.swing.JLabel Estrella4;
    private javax.swing.JLabel NombreUsuario1;
    private javax.swing.JLabel NombreUsuario2;
    private javax.swing.JLabel PuntuacionGeneral;
    private javax.swing.JLabel PuntuacionUsuario1;
    private javax.swing.JLabel PuntuacionUsuario2;
    private javax.swing.JTextArea ResenaAEscribir;
    private javax.swing.JTextPane ResenaUsuario1;
    private javax.swing.JTextPane ResenaUsuario2;
    private javax.swing.JLabel TituloItem_Tipo;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel Estrella5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
      private javax.swing.JTextField Titulo_resena;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea Texto_resena_otro;
     private javax.swing.JLabel estrella1;
    private javax.swing.JLabel estrella2;
    private javax.swing.JLabel estrella3;
    private javax.swing.JLabel estrella4;
    private javax.swing.JLabel estrella5;
    private javax.swing.JLabel Titulo_resena_otro;
     private javax.swing.JPanel PanelEstrellasMario;
    // End of variables declaration                   
}

